### ISSUE TITLE
The program doesn't detect my IP address:

### ISSUE THREAD

**Issue by lightyisreal** [Aioros/console-streaming-server#7]
Hi, I would love to use this program, but I'm facing an issue. I ran the software from source so that I could see why it was not working, and this is what I got:

```
12/21/2024 16:55:57 16584 [ERROR] uncaughtException TypeError [ERR_INVALID_ARG_TYPE]: The "servers[0]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at node:internal/dns/utils:104:7
    at Array.forEach (<anonymous>)
    at Resolver.setServers (node:internal/dns/utils:103:5)
    at ConsoleStreamingServer.checkDNSStatus (D:\Projects\console-streaming-server\console-streaming-server.js:137:22)
    at ConsoleStreamingServer.checkStatus (D:\Projects\console-streaming-server\console-streaming-server.js:253:14)
    at Timeout._onTimeout (D:\Projects\console-streaming-server\gui.js:407:22)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  code: 'ERR_INVALID_ARG_TYPE'
```

**Comment by lightyisreal** [comment]
Oh, and even when I force it by assigning it a manual IP address, I get this error:

```
  dnsproxy:query type: server, domain: *contribute.live-video.net, answer: undefined, source: 192.168.1.14:59592, size: 44 +47ms
12/21/2024 17:02:21 17304 [ERROR] uncaughtException AssertionError [ERR_ASSERTION]: A/AAAA record requires "address"
    at assertUndefined (D:\Projects\console-streaming-server\node_modules\native-dns-packet\packet.js:36:3)
    at writeIp (D:\Projects\console-streaming-server\node_modules\native-dns-packet\packet.js:265:3)
    at Packet.write (D:\Projects\console-streaming-server\node_modules\native-dns-packet\packet.js:455:19)
    at module.exports.createAnswer (D:\Projects\console-streaming-server\node_modules\@aiorosdev\dns-proxy-lib\util.js:30:22)
    at D:\Projects\console-streaming-server\node_modules\@aiorosdev\dns-proxy-lib\dns-proxy.js:120:26
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (D:\Projects\console-streaming-server\node_modules\@aiorosdev\dns-proxy-lib\dns-proxy.js:108:33)
    at Socket.emit (node:events:513:28)
    at UDP.onMessage [as onmessage] (node:dgram:930:8) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
```
